import localFont from 'next/font/local'

const geomanist = localFont({
  src: [
    {
      path: './fonts/Geomanist-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/Geomanist-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/Geomanist-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: './fonts/Geomanist-Black.woff2',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-geomanist',
  display: 'swap',
})
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={[geomanist.className, "antialiased"].join(" ")}>
        {children}
      </body>
    </html>
  );
}
